INSERT INTO regiones (id, nombre) VALUES (1, 'Miranda');

INSERT INTO pais (id, nombre) VALUES (144, 'Afganistán');
INSERT INTO pais (id, nombre) VALUES (114, 'Albania');
INSERT INTO pais (id, nombre) VALUES (18, 'Alemania');
INSERT INTO pais (id, nombre) VALUES (98, 'Algeria');
INSERT INTO pais (id, nombre) VALUES (145, 'Andorra');
INSERT INTO pais (id, nombre) VALUES (119, 'Angola');
INSERT INTO pais (id, nombre) VALUES (4, 'Anguilla');
INSERT INTO pais (id, nombre) VALUES (147, 'Antigua y Barbuda');
INSERT INTO pais (id, nombre) VALUES (207, 'Antillas Holandesas');
INSERT INTO pais (id, nombre) VALUES (91, 'Arabia Saudita');
INSERT INTO pais (id, nombre) VALUES (5, 'Argentina');
INSERT INTO pais (id, nombre) VALUES (6, 'Armenia');
INSERT INTO pais (id, nombre) VALUES (142, 'Aruba');
INSERT INTO pais (id, nombre) VALUES (1, 'Australia');
INSERT INTO pais (id, nombre) VALUES (2, 'Austria');
INSERT INTO pais (id, nombre) VALUES (3, 'Azerbaiyán');
INSERT INTO pais (id, nombre) VALUES (80, 'Bahamas');
INSERT INTO pais (id, nombre) VALUES (127, 'Bahrein');
INSERT INTO pais (id, nombre) VALUES (149, 'Bangladesh');
INSERT INTO pais (id, nombre) VALUES (128, 'Barbados');
INSERT INTO pais (id, nombre) VALUES (9, 'Bélgica');
INSERT INTO pais (id, nombre) VALUES (8, 'Belice');
INSERT INTO pais (id, nombre) VALUES (151, 'Benín');
INSERT INTO pais (id, nombre) VALUES (10, 'Bermudas');
INSERT INTO pais (id, nombre) VALUES (7, 'Bielorrusia');
INSERT INTO pais (id, nombre) VALUES (123, 'Bolivia');
INSERT INTO pais (id, nombre) VALUES (79, 'Bosnia y Herzegovina');
INSERT INTO pais (id, nombre) VALUES (100, 'Botsuana');
INSERT INTO pais (id, nombre) VALUES (12, 'Brasil');
INSERT INTO pais (id, nombre) VALUES (155, 'Brunéi');
INSERT INTO pais (id, nombre) VALUES (11, 'Bulgaria');
INSERT INTO pais (id, nombre) VALUES (156, 'Burkina Faso');
INSERT INTO pais (id, nombre) VALUES (157, 'Burundi');
INSERT INTO pais (id, nombre) VALUES (152, 'Bután');
INSERT INTO pais (id, nombre) VALUES (159, 'Cabo Verde');
INSERT INTO pais (id, nombre) VALUES (158, 'Camboya');
INSERT INTO pais (id, nombre) VALUES (31, 'Camerún');
INSERT INTO pais (id, nombre) VALUES (32, 'Canadá');
INSERT INTO pais (id, nombre) VALUES (130, 'Chad');
INSERT INTO pais (id, nombre) VALUES (81, 'Chile');
INSERT INTO pais (id, nombre) VALUES (35, 'China');
INSERT INTO pais (id, nombre) VALUES (33, 'Chipre');
INSERT INTO pais (id, nombre) VALUES (82, 'Colombia');
INSERT INTO pais (id, nombre) VALUES (164, 'Comores');
INSERT INTO pais (id, nombre) VALUES (112, 'Congo (Brazzaville)');
INSERT INTO pais (id, nombre) VALUES (165, 'Congo (Kinshasa)');
INSERT INTO pais (id, nombre) VALUES (166, 'Cook, Islas');
INSERT INTO pais (id, nombre) VALUES (84, 'Corea del Norte');
INSERT INTO pais (id, nombre) VALUES (69, 'Corea del Sur');
INSERT INTO pais (id, nombre) VALUES (168, 'Costa de Marfil');
INSERT INTO pais (id, nombre) VALUES (36, 'Costa Rica');
INSERT INTO pais (id, nombre) VALUES (71, 'Croacia');
INSERT INTO pais (id, nombre) VALUES (113, 'Cuba');
INSERT INTO pais (id, nombre) VALUES (22, 'Dinamarca');
INSERT INTO pais (id, nombre) VALUES (169, 'Djibouti, Yibuti');
INSERT INTO pais (id, nombre) VALUES (103, 'Ecuador');
INSERT INTO pais (id, nombre) VALUES (23, 'Egipto');
INSERT INTO pais (id, nombre) VALUES (51, 'El Salvador');
INSERT INTO pais (id, nombre) VALUES (93, 'Emiratos Árabes Unidos');
INSERT INTO pais (id, nombre) VALUES (173, 'Eritrea');
INSERT INTO pais (id, nombre) VALUES (52, 'Eslovaquia');
INSERT INTO pais (id, nombre) VALUES (53, 'Eslovenia');
INSERT INTO pais (id, nombre) VALUES (28, 'España');
INSERT INTO pais (id, nombre) VALUES (55, 'Estados Unidos');
INSERT INTO pais (id, nombre) VALUES (68, 'Estonia');
INSERT INTO pais (id, nombre) VALUES (121, 'Etiopía');
INSERT INTO pais (id, nombre) VALUES (175, 'Feroe, Islas');
INSERT INTO pais (id, nombre) VALUES (90, 'Filipinas');
INSERT INTO pais (id, nombre) VALUES (63, 'Finlandia');
INSERT INTO pais (id, nombre) VALUES (176, 'Fiyi');
INSERT INTO pais (id, nombre) VALUES (64, 'Francia');
INSERT INTO pais (id, nombre) VALUES (180, 'Gabón');
INSERT INTO pais (id, nombre) VALUES (181, 'Gambia');
INSERT INTO pais (id, nombre) VALUES (21, 'Georgia');
INSERT INTO pais (id, nombre) VALUES (105, 'Ghana');
INSERT INTO pais (id, nombre) VALUES (143, 'Gibraltar');
INSERT INTO pais (id, nombre) VALUES (184, 'Granada');
INSERT INTO pais (id, nombre) VALUES (20, 'Grecia');
INSERT INTO pais (id, nombre) VALUES (94, 'Groenlandia');
INSERT INTO pais (id, nombre) VALUES (17, 'Guadalupe');
INSERT INTO pais (id, nombre) VALUES (185, 'Guatemala');
INSERT INTO pais (id, nombre) VALUES (186, 'Guernsey');
INSERT INTO pais (id, nombre) VALUES (187, 'Guinea');
INSERT INTO pais (id, nombre) VALUES (172, 'Guinea Ecuatorial');
INSERT INTO pais (id, nombre) VALUES (188, 'Guinea-Bissau');
INSERT INTO pais (id, nombre) VALUES (189, 'Guyana');
INSERT INTO pais (id, nombre) VALUES (16, 'Haiti');
INSERT INTO pais (id, nombre) VALUES (137, 'Honduras');
INSERT INTO pais (id, nombre) VALUES (73, 'Hong Kong');
INSERT INTO pais (id, nombre) VALUES (14, 'Hungría');
INSERT INTO pais (id, nombre) VALUES (25, 'India');
INSERT INTO pais (id, nombre) VALUES (74, 'Indonesia');
INSERT INTO pais (id, nombre) VALUES (140, 'Irak');
INSERT INTO pais (id, nombre) VALUES (26, 'Irán');
INSERT INTO pais (id, nombre) VALUES (27, 'Irlanda');
INSERT INTO pais (id, nombre) VALUES (215, 'Isla Pitcairn');
INSERT INTO pais (id, nombre) VALUES (83, 'Islandia');
INSERT INTO pais (id, nombre) VALUES (228, 'Islas Salomón');
INSERT INTO pais (id, nombre) VALUES (58, 'Islas Turcas y Caicos');
INSERT INTO pais (id, nombre) VALUES (154, 'Islas Virgenes Británicas');
INSERT INTO pais (id, nombre) VALUES (24, 'Israel');
INSERT INTO pais (id, nombre) VALUES (29, 'Italia');
INSERT INTO pais (id, nombre) VALUES (132, 'Jamaica');
INSERT INTO pais (id, nombre) VALUES (70, 'Japón');
INSERT INTO pais (id, nombre) VALUES (193, 'Jersey');
INSERT INTO pais (id, nombre) VALUES (75, 'Jordania');
INSERT INTO pais (id, nombre) VALUES (30, 'Kazajstán');
INSERT INTO pais (id, nombre) VALUES (97, 'Kenia');
INSERT INTO pais (id, nombre) VALUES (34, 'Kirguistán');
INSERT INTO pais (id, nombre) VALUES (195, 'Kiribati');
INSERT INTO pais (id, nombre) VALUES (37, 'Kuwait');
INSERT INTO pais (id, nombre) VALUES (196, 'Laos');
INSERT INTO pais (id, nombre) VALUES (197, 'Lesotho');
INSERT INTO pais (id, nombre) VALUES (38, 'Letonia');
INSERT INTO pais (id, nombre) VALUES (99, 'Líbano');
INSERT INTO pais (id, nombre) VALUES (198, 'Liberia');
INSERT INTO pais (id, nombre) VALUES (39, 'Libia');
INSERT INTO pais (id, nombre) VALUES (126, 'Liechtenstein');
INSERT INTO pais (id, nombre) VALUES (40, 'Lituania');
INSERT INTO pais (id, nombre) VALUES (41, 'Luxemburgo');
INSERT INTO pais (id, nombre) VALUES (85, 'Macedonia');
INSERT INTO pais (id, nombre) VALUES (134, 'Madagascar');
INSERT INTO pais (id, nombre) VALUES (76, 'Malasia');
INSERT INTO pais (id, nombre) VALUES (125, 'Malawi');
INSERT INTO pais (id, nombre) VALUES (200, 'Maldivas');
INSERT INTO pais (id, nombre) VALUES (133, 'Malí');
INSERT INTO pais (id, nombre) VALUES (86, 'Malta');
INSERT INTO pais (id, nombre) VALUES (131, 'Man, Isla de');
INSERT INTO pais (id, nombre) VALUES (104, 'Marruecos');
INSERT INTO pais (id, nombre) VALUES (201, 'Martinica');
INSERT INTO pais (id, nombre) VALUES (202, 'Mauricio');
INSERT INTO pais (id, nombre) VALUES (108, 'Mauritania');
INSERT INTO pais (id, nombre) VALUES (42, 'México');
INSERT INTO pais (id, nombre) VALUES (43, 'Moldavia');
INSERT INTO pais (id, nombre) VALUES (44, 'Mónaco');
INSERT INTO pais (id, nombre) VALUES (139, 'Mongolia');
INSERT INTO pais (id, nombre) VALUES (117, 'Mozambique');
INSERT INTO pais (id, nombre) VALUES (205, 'Myanmar');
INSERT INTO pais (id, nombre) VALUES (102, 'Namibia');
INSERT INTO pais (id, nombre) VALUES (206, 'Nauru');
INSERT INTO pais (id, nombre) VALUES (107, 'Nepal');
INSERT INTO pais (id, nombre) VALUES (209, 'Nicaragua');
INSERT INTO pais (id, nombre) VALUES (210, 'Níger');
INSERT INTO pais (id, nombre) VALUES (115, 'Nigeria');
INSERT INTO pais (id, nombre) VALUES (212, 'Norfolk Island');
INSERT INTO pais (id, nombre) VALUES (46, 'Noruega');
INSERT INTO pais (id, nombre) VALUES (208, 'Nueva Caledonia');
INSERT INTO pais (id, nombre) VALUES (45, 'Nueva Zelanda');
INSERT INTO pais (id, nombre) VALUES (213, 'Omán');
INSERT INTO pais (id, nombre) VALUES (19, 'Países Bajos, Holanda');
INSERT INTO pais (id, nombre) VALUES (87, 'Pakistán');
INSERT INTO pais (id, nombre) VALUES (124, 'Panamá');
INSERT INTO pais (id, nombre) VALUES (88, 'Papúa-Nueva Guinea');
INSERT INTO pais (id, nombre) VALUES (110, 'Paraguay');
INSERT INTO pais (id, nombre) VALUES (89, 'Perú');
INSERT INTO pais (id, nombre) VALUES (178, 'Polinesia Francesa');
INSERT INTO pais (id, nombre) VALUES (47, 'Polonia');
INSERT INTO pais (id, nombre) VALUES (48, 'Portugal');
INSERT INTO pais (id, nombre) VALUES (246, 'Puerto Rico');
INSERT INTO pais (id, nombre) VALUES (216, 'Qatar');
INSERT INTO pais (id, nombre) VALUES (13, 'Reino Unido');
INSERT INTO pais (id, nombre) VALUES (65, 'República Checa');
INSERT INTO pais (id, nombre) VALUES (138, 'República Dominicana');
INSERT INTO pais (id, nombre) VALUES (49, 'Reunión');
INSERT INTO pais (id, nombre) VALUES (217, 'Ruanda');
INSERT INTO pais (id, nombre) VALUES (72, 'Rumanía');
INSERT INTO pais (id, nombre) VALUES (50, 'Rusia');
INSERT INTO pais (id, nombre) VALUES (242, 'Sáhara Occidental');
INSERT INTO pais (id, nombre) VALUES (223, 'Samoa');
INSERT INTO pais (id, nombre) VALUES (219, 'San Cristobal y Nevis');
INSERT INTO pais (id, nombre) VALUES (224, 'San Marino');
INSERT INTO pais (id, nombre) VALUES (221, 'San Pedro y Miquelón');
INSERT INTO pais (id, nombre) VALUES (225, 'San Tomé y Príncipe');
INSERT INTO pais (id, nombre) VALUES (222, 'San Vincente y Granadinas');
INSERT INTO pais (id, nombre) VALUES (218, 'Santa Elena');
INSERT INTO pais (id, nombre) VALUES (220, 'Santa Lucía');
INSERT INTO pais (id, nombre) VALUES (135, 'Senegal');
INSERT INTO pais (id, nombre) VALUES (226, 'Serbia y Montenegro');
INSERT INTO pais (id, nombre) VALUES (109, 'Seychelles');
INSERT INTO pais (id, nombre) VALUES (227, 'Sierra Leona');
INSERT INTO pais (id, nombre) VALUES (77, 'Singapur');
INSERT INTO pais (id, nombre) VALUES (106, 'Siria');
INSERT INTO pais (id, nombre) VALUES (229, 'Somalia');
INSERT INTO pais (id, nombre) VALUES (120, 'Sri Lanka');
INSERT INTO pais (id, nombre) VALUES (141, 'Sudáfrica');
INSERT INTO pais (id, nombre) VALUES (232, 'Sudán');
INSERT INTO pais (id, nombre) VALUES (67, 'Suecia');
INSERT INTO pais (id, nombre) VALUES (66, 'Suiza');
INSERT INTO pais (id, nombre) VALUES (54, 'Surinam');
INSERT INTO pais (id, nombre) VALUES (234, 'Swazilandia');
INSERT INTO pais (id, nombre) VALUES (56, 'Tadjikistan');
INSERT INTO pais (id, nombre) VALUES (92, 'Tailandia');
INSERT INTO pais (id, nombre) VALUES (78, 'Taiwan');
INSERT INTO pais (id, nombre) VALUES (101, 'Tanzania');
INSERT INTO pais (id, nombre) VALUES (171, 'Timor Oriental');
INSERT INTO pais (id, nombre) VALUES (136, 'Togo');
INSERT INTO pais (id, nombre) VALUES (235, 'Tokelau');
INSERT INTO pais (id, nombre) VALUES (236, 'Tonga');
INSERT INTO pais (id, nombre) VALUES (237, 'Trinidad y Tobago');
INSERT INTO pais (id, nombre) VALUES (122, 'Túnez');
INSERT INTO pais (id, nombre) VALUES (57, 'Turkmenistan');
INSERT INTO pais (id, nombre) VALUES (59, 'Turquía');
INSERT INTO pais (id, nombre) VALUES (239, 'Tuvalu');
INSERT INTO pais (id, nombre) VALUES (62, 'Ucrania');
INSERT INTO pais (id, nombre) VALUES (60, 'Uganda');
INSERT INTO pais (id, nombre) VALUES (111, 'Uruguay');
INSERT INTO pais (id, nombre) VALUES (61, 'Uzbekistán');
INSERT INTO pais (id, nombre) VALUES (240, 'Vanuatu');
INSERT INTO pais (id, nombre) VALUES (95, 'Venezuela');
INSERT INTO pais (id, nombre) VALUES (15, 'Vietnam');
INSERT INTO pais (id, nombre) VALUES (241, 'Wallis y Futuna');
INSERT INTO pais (id, nombre) VALUES (243, 'Yemen');
INSERT INTO pais (id, nombre) VALUES (116, 'Zambia');
INSERT INTO pais (id, nombre) VALUES (96, 'Zimbabwe');

INSERT INTO registros (pais_id, region_id, nombre, apellido, tipo_documento, numero_documento, email, pass, terminos) VALUES(1, 1, 'dayana', 'sanchez', '2', '269624035', 'dayanalily22@gmail.com', '12345', true );


INSERT INTO usuarios (id, email, password, enabled, nombre, apellido, tipo_documento, numero_documento, terminos, foto, ocupacion, nombre_empresa, telefono, direccion, cuidad, estado, codigo_postal, linkedink,facebook, instagram, twittter, pais) VALUES (1, 'dayanalily22@gmail.com', '$2a$10$t2DCLCYLA9f3J32LkTwftOJPB7LeC6qZ9xW3.jm2d8kgX04Uxv656', 1, 'dayana', 'sanchez', 1, '34567878787', true , '', '', '', '', '', '', '', '', '', '', '', '','venezuela');
INSERT INTO usuarios (id, email, password, enabled, nombre, apellido, tipo_documento, numero_documento, terminos, foto, ocupacion, nombre_empresa, telefono, direccion, cuidad, estado, codigo_postal, linkedink,facebook, instagram, twittter, pais) VALUES (2, 'dayanalily22@hotmail.com', '$2a$10$MyBX0BbD7DfHi6XuawQikulCpWUnupd9CYdT3STtF7Ki/wII1vZCC', 1, 'dayanaadmin', 'sanchez', 1,'269624056', true , '', '', '', '', '', '', '', '', '', '', '', '','chile');
INSERT INTO usuarios (id, email, password, enabled, nombre, apellido, tipo_documento, numero_documento, terminos, foto, ocupacion, nombre_empresa, telefono, direccion, cuidad, estado, codigo_postal, linkedink,facebook, instagram, twittter, pais) VALUES (3, 'dailysanemail@gmail.com', '$2a$10$4jSA6bXlkNAlQLauH5QcXeYLprfT1ZXesT2xt13yrZVhHtbHDr2Ee', 1,'dayanados', 'sanchez', 1, '269624035', true , '', '', '', '', '', '', '', '', '', '', '', '','venezuela');


INSERT INTO roles (id, nombre) VALUES (1, 'ROLE_USER');
INSERT INTO roles (id, nombre) VALUES (2, 'ROLE_ADMIN');



INSERT INTO usuario_roles (usuario_id, role_id) VALUES (1,1);
INSERT INTO usuario_roles (usuario_id, role_id) VALUES (1,2);
INSERT INTO usuario_roles (usuario_id, role_id) VALUES (2,1);
INSERT INTO usuario_roles (usuario_id, role_id) VALUES (2,2);


